/*
 * OpenBankProject-Bank
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AccountV310Json struct {
	AccountRoutings *Array `json:"account_routings,omitempty"`
	AccountType string `json:"account_type,omitempty"`
	BankId string `json:"bank_id,omitempty"`
	AccountId string `json:"account_id,omitempty"`
	BranchRoutings *Array `json:"branch_routings,omitempty"`
}
