/*
 * OpenBankProject-FirehoseData
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TransactionMetadataJson struct {
	Narrative string `json:"narrative,omitempty"`
	Tags *Array `json:"tags,omitempty"`
	Where * `json:"where,omitempty"`
	Images *Array `json:"images,omitempty"`
	Comments *Array `json:"comments,omitempty"`
}
