/*
 * OpenBankProject-Counterparty-Metadata
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CounterpartyWithMetadataJson struct {
	OtherAccountRoutingAddress string `json:"other_account_routing_address,omitempty"`
	OtherAccountRoutingScheme string `json:"other_account_routing_scheme,omitempty"`
	CreatedByUserId string `json:"created_by_user_id,omitempty"`
	Name string `json:"name,omitempty"`
	OtherAccountSecondaryRoutingAddress string `json:"other_account_secondary_routing_address,omitempty"`
	IsBeneficiary bool `json:"is_beneficiary,omitempty"`
	Description string `json:"description,omitempty"`
	OtherBranchRoutingAddress string `json:"other_branch_routing_address,omitempty"`
	Bespoke *Array `json:"bespoke,omitempty"`
	OtherBankRoutingScheme string `json:"other_bank_routing_scheme,omitempty"`
	OtherBranchRoutingScheme string `json:"other_branch_routing_scheme,omitempty"`
	ThisAccountId string `json:"this_account_id,omitempty"`
	ThisViewId string `json:"this_view_id,omitempty"`
	Metadata * `json:"metadata,omitempty"`
	OtherBankRoutingAddress string `json:"other_bank_routing_address,omitempty"`
	ThisBankId string `json:"this_bank_id,omitempty"`
	CounterpartyId string `json:"counterparty_id,omitempty"`
	OtherAccountSecondaryRoutingScheme string `json:"other_account_secondary_routing_scheme,omitempty"`
}
