/*
 * OpenBankProject-API-Metric
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MetricJson struct {
	Duration int32 `json:"duration,omitempty"`
	ImplementedInVersion string `json:"implemented_in_version,omitempty"`
	Url string `json:"url,omitempty"`
	CorrelationId string `json:"correlation_id,omitempty"`
	ImplementedByPartialFunction string `json:"implemented_by_partial_function,omitempty"`
	UserId string `json:"user_id,omitempty"`
	DeveloperEmail string `json:"developer_email,omitempty"`
	Date string `json:"date,omitempty"`
	ConsumerId string `json:"consumer_id,omitempty"`
	Verb string `json:"verb,omitempty"`
	AppName string `json:"app_name,omitempty"`
	UserName string `json:"user_name,omitempty"`
}
