/*
 * OpenBankProject-Bank
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TransactionType struct {
	ShortCode string `json:"shortCode,omitempty"`
	Description string `json:"description,omitempty"`
	TransactionTypeId *interface{} `json:"TransactionTypeId,omitempty"`
	Id * `json:"id,omitempty"`
	Charge * `json:"charge,omitempty"`
	BankId * `json:"bankId,omitempty"`
	Summary string `json:"summary,omitempty"`
}
