/*
 * OpenBankProject-Bank-FX
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FxRateJsonV220 struct {
	InverseConversionValue float64 `json:"inverse_conversion_value,omitempty"`
	ToCurrencyCode string `json:"to_currency_code,omitempty"`
	EffectiveDate string `json:"effective_date,omitempty"`
	ConversionValue float64 `json:"conversion_value,omitempty"`
	BankId string `json:"bank_id,omitempty"`
	FromCurrencyCode string `json:"from_currency_code,omitempty"`
}
