/*
 * OpenBankProject-FirehoseData
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LocationJsonv121 struct {
	UserJSONV121 *interface{} `json:"UserJSONV121,omitempty"`
	User * `json:"user,omitempty"`
	Date string `json:"date,omitempty"`
	Longitude float64 `json:"longitude,omitempty"`
	Latitude float64 `json:"latitude,omitempty"`
}
