/*
 * OpenBankProject-FirehoseData
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OtherAccountJsonV300 struct {
	AccountRoutings *Array `json:"account_routings,omitempty"`
	AccountHolderJSON *interface{} `json:"AccountHolderJSON,omitempty"`
	Holder * `json:"holder,omitempty"`
	Id string `json:"id,omitempty"`
	Metadata * `json:"metadata,omitempty"`
	BankRoutingJsonV121 *interface{} `json:"BankRoutingJsonV121,omitempty"`
	BankRouting * `json:"bank_routing,omitempty"`
}
