/*
 * OpenBankProject-Bank-Branch
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BranchRoutingJsonV141 struct {
	Address string `json:"address,omitempty"`
	Scheme string `json:"scheme,omitempty"`
}
