/*
 * OpenBankProject-User
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AccountJson struct {
	BankId string `json:"bank_id,omitempty"`
	ViewsAvailable *Array `json:"views_available,omitempty"`
	Label string `json:"label,omitempty"`
	Id string `json:"id,omitempty"`
}
