/*
 * OpenBankProject-User
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CustomerJsonV210 struct {
	CustomerId string `json:"customer_id,omitempty"`
	Email string `json:"email,omitempty"`
	MobilePhoneNumber string `json:"mobile_phone_number,omitempty"`
	CustomerNumber string `json:"customer_number,omitempty"`
	HighestEducationAttained string `json:"highest_education_attained,omitempty"`
	DobOfDependants *Array `json:"dob_of_dependants,omitempty"`
	BankId string `json:"bank_id,omitempty"`
	DateOfBirth string `json:"date_of_birth,omitempty"`
	CreditRating * `json:"credit_rating,omitempty"`
	LastOkDate string `json:"last_ok_date,omitempty"`
	EmploymentStatus string `json:"employment_status,omitempty"`
	LegalName string `json:"legal_name,omitempty"`
	CreditLimit * `json:"credit_limit,omitempty"`
	FaceImage * `json:"face_image,omitempty"`
	Dependants int32 `json:"dependants,omitempty"`
	RelationshipStatus string `json:"relationship_status,omitempty"`
	KycStatus bool `json:"kyc_status,omitempty"`
}
