/*
 * OpenBankProject-Bank-Branch
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BranchJsonPutV210 struct {
	Name string `json:"name,omitempty"`
	Location * `json:"location,omitempty"`
	DriveUp * `json:"drive_up,omitempty"`
	BankId string `json:"bank_id,omitempty"`
	Meta * `json:"meta,omitempty"`
	Lobby * `json:"lobby,omitempty"`
	Address * `json:"address,omitempty"`
}
