/*
 * OpenBankProject-Bank-Branch
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BranchJson struct {
	Name string `json:"name,omitempty"`
	LocationJsonV140 *interface{} `json:"LocationJsonV140,omitempty"`
	Location * `json:"location,omitempty"`
	BranchRouting * `json:"branch_routing,omitempty"`
	DriveUpStringJson *interface{} `json:"DriveUpStringJson,omitempty"`
	DriveUp * `json:"drive_up,omitempty"`
	Id string `json:"id,omitempty"`
	MetaJsonV140 *interface{} `json:"MetaJsonV140,omitempty"`
	Meta * `json:"meta,omitempty"`
	LobbyStringJson *interface{} `json:"LobbyStringJson,omitempty"`
	Lobby * `json:"lobby,omitempty"`
	AddressJsonV140 *interface{} `json:"AddressJsonV140,omitempty"`
	Address * `json:"address,omitempty"`
}
