/*
 * OpenBankProject-Counterparty
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OtherAccountJson struct {
	Number string `json:"number,omitempty"`
	IBAN string `json:"IBAN,omitempty"`
	SwiftBic string `json:"swift_bic,omitempty"`
	Holder * `json:"holder,omitempty"`
	Bank * `json:"bank,omitempty"`
	Id string `json:"id,omitempty"`
	OtherAccountMetadataJSON *interface{} `json:"OtherAccountMetadataJSON,omitempty"`
	Metadata * `json:"metadata,omitempty"`
	Kind string `json:"kind,omitempty"`
}
