/*
 * OpenBankProject-Bank
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OrderObjectJson struct {
	OrderId string `json:"order_id,omitempty"`
	NumberOfCheckbooks string `json:"number_of_checkbooks,omitempty"`
	FirstCheckNumber string `json:"first_check_number,omitempty"`
	OrderDate string `json:"order_date,omitempty"`
	Status string `json:"status,omitempty"`
	ShippingCode string `json:"shipping_code,omitempty"`
	DistributionChannel string `json:"distribution_channel,omitempty"`
}
