/*
 * OpenBankProject-User
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateUserJson struct {
	FirstName string `json:"first_name,omitempty"`
	Email string `json:"email,omitempty"`
	Username string `json:"username,omitempty"`
	LastName string `json:"last_name,omitempty"`
	Password string `json:"password,omitempty"`
}
