/*
 * OpenBankProject-Account-View
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateViewJson struct {
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	IsPublic bool `json:"is_public,omitempty"`
	HideMetadataIfAliasUsed bool `json:"hide_metadata_if_alias_used,omitempty"`
	WhichAliasToUse string `json:"which_alias_to_use,omitempty"`
	MetadataView string `json:"metadata_view,omitempty"`
	AllowedActions *Array `json:"allowed_actions,omitempty"`
}
