/*
 * OpenBankProject-API-Sandbox
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SandboxDataImport struct {
	CrmEvents *Array `json:"crm_events,omitempty"`
	Users *Array `json:"users,omitempty"`
	Products *Array `json:"products,omitempty"`
	Banks *Array `json:"banks,omitempty"`
	Branches *Array `json:"branches,omitempty"`
	Transactions *Array `json:"transactions,omitempty"`
	Accounts *Array `json:"accounts,omitempty"`
	Atms *Array `json:"atms,omitempty"`
}
