/*
 * OpenBankProject-Bank-Branch
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OpeningTimesV300 struct {
	ClosingTime string `json:"closing_time,omitempty"`
	OpeningTime string `json:"opening_time,omitempty"`
}
