/*
 * OpenBankProject-User
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MeetingJson struct {
	Present * `json:"present,omitempty"`
	ProviderId string `json:"provider_id,omitempty"`
	BankId string `json:"bank_id,omitempty"`
	PurposeId string `json:"purpose_id,omitempty"`
	When string `json:"when,omitempty"`
	MeetingId string `json:"meeting_id,omitempty"`
	Keys * `json:"keys,omitempty"`
}
