/*
 * OpenBankProject-User
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserJsonv121 struct {
	DisplayName string `json:"display_name,omitempty"`
	Provider string `json:"provider,omitempty"`
	Id string `json:"id,omitempty"`
}
