/*
 * OpenBankProject-Bank
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CardObjectJson struct {
	UseType string `json:"use_type,omitempty"`
	CardDescription string `json:"card_description,omitempty"`
	CardType string `json:"card_type,omitempty"`
}
