/*
 * OpenBankProject-User
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserCustomerLinkJson struct {
	IsActive bool `json:"is_active,omitempty"`
	CustomerId string `json:"customer_id,omitempty"`
	UserId string `json:"user_id,omitempty"`
	DateInserted string `json:"date_inserted,omitempty"`
	UserCustomerLinkId string `json:"user_customer_link_id,omitempty"`
}
