/*
 * OpenBankProject-Bank
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TransactionTypesJsonV200 struct {
	TransactionTypes *Array `json:"transaction_types,omitempty"`
}
