/*
 * OpenBankProject-Bank-Branch
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DriveUpJsonV330 struct {
	Sunday * `json:"sunday,omitempty"`
	Tuesday * `json:"tuesday,omitempty"`
	Wednesday * `json:"wednesday,omitempty"`
	Monday * `json:"monday,omitempty"`
	Friday * `json:"friday,omitempty"`
	Thursday * `json:"thursday,omitempty"`
	Saturday * `json:"saturday,omitempty"`
}
