/*
 * OpenBankProject-API-Metric
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TopConsumerJson struct {
	DeveloperEmail string `json:"developer_email,omitempty"`
	AppName string `json:"app_name,omitempty"`
	ConsumerId string `json:"consumer_id,omitempty"`
	Count int32 `json:"count,omitempty"`
}
