/*
 * OpenBankProject-Bank-Branch
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LobbyJsonV330 struct {
	Sunday *Array `json:"sunday,omitempty"`
	Tuesday *Array `json:"tuesday,omitempty"`
	Wednesday *Array `json:"wednesday,omitempty"`
	Monday *Array `json:"monday,omitempty"`
	Friday *Array `json:"friday,omitempty"`
	Thursday *Array `json:"thursday,omitempty"`
	Saturday *Array `json:"saturday,omitempty"`
}
