/*
 * OpenBankProject-Account-View
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AccountHeldJson struct {
	AccountRoutings *Array `json:"account_routings,omitempty"`
	Number string `json:"number,omitempty"`
	BankId string `json:"bank_id,omitempty"`
	Id string `json:"id,omitempty"`
}
