/*
 * OpenBankProject-User
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ScopeJson struct {
	BankId string `json:"bank_id,omitempty"`
	RoleName string `json:"role_name,omitempty"`
	ScopeId string `json:"scope_id,omitempty"`
}
