/*
 * OpenBankProject-Bank
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TransactionTypeJsonV200 struct {
	Description string `json:"description,omitempty"`
	ShortCode string `json:"short_code,omitempty"`
	BankId string `json:"bank_id,omitempty"`
	Id * `json:"id,omitempty"`
	Charge * `json:"charge,omitempty"`
	Summary string `json:"summary,omitempty"`
}
