/*
 * OpenBankProject-FirehoseData
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OtherAccountMetadataJson struct {
	PublicAlias string `json:"public_alias,omitempty"`
	ImageURL string `json:"image_URL,omitempty"`
	LocationJSONV121 *interface{} `json:"LocationJSONV121,omitempty"`
	PhysicalLocation * `json:"physical_location,omitempty"`
	PrivateAlias string `json:"private_alias,omitempty"`
	URL string `json:"URL,omitempty"`
	MoreInfo string `json:"more_info,omitempty"`
	CorporateLocation * `json:"corporate_location,omitempty"`
	OpenCorporatesURL string `json:"open_corporates_URL,omitempty"`
}
