/*
 * OpenBankProject-Counterparty
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PostCounterpartyJson struct {
	OtherAccountRoutingAddress string `json:"other_account_routing_address,omitempty"`
	OtherAccountRoutingScheme string `json:"other_account_routing_scheme,omitempty"`
	Name string `json:"name,omitempty"`
	OtherAccountSecondaryRoutingAddress string `json:"other_account_secondary_routing_address,omitempty"`
	IsBeneficiary bool `json:"is_beneficiary,omitempty"`
	Description string `json:"description,omitempty"`
	OtherBranchRoutingAddress string `json:"other_branch_routing_address,omitempty"`
	Bespoke *Array `json:"bespoke,omitempty"`
	OtherBankRoutingScheme string `json:"other_bank_routing_scheme,omitempty"`
	OtherBranchRoutingScheme string `json:"other_branch_routing_scheme,omitempty"`
	OtherBankRoutingAddress string `json:"other_bank_routing_address,omitempty"`
	OtherAccountSecondaryRoutingScheme string `json:"other_account_secondary_routing_scheme,omitempty"`
}
