/*
 * OpenBankProject-Bank
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreditLimitOrderRequestJson struct {
	RequestedCurrentRateAmount1 string `json:"requested_current_rate_amount1,omitempty"`
	TemporaryCreditDocumentation string `json:"temporary_credit_documentation,omitempty"`
	RequestedCurrentValidEndDate string `json:"requested_current_valid_end_date,omitempty"`
	TemporaryRequestedCurrentAmount string `json:"temporary_requested_current_amount,omitempty"`
	RequestedCurrentRateAmount2 string `json:"requested_current_rate_amount2,omitempty"`
	RequestedTemporaryValidEndDate string `json:"requested_temporary_valid_end_date,omitempty"`
	CurrentCreditDocumentation string `json:"current_credit_documentation,omitempty"`
}
