/*
 * OpenBankProject-User
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserJsonV200 struct {
	Provider string `json:"provider,omitempty"`
	Email string `json:"email,omitempty"`
	Username string `json:"username,omitempty"`
	ProviderId string `json:"provider_id,omitempty"`
	UserId string `json:"user_id,omitempty"`
	Entitlements * `json:"entitlements,omitempty"`
}
