/*
 * OpenBankProject-FirehoseData
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TransactionDetailsJson struct {
	NewBalance * `json:"new_balance,omitempty"`
	Description string `json:"description,omitempty"`
	Completed string `json:"completed,omitempty"`
	Type_ string `json:"type,omitempty"`
	Value * `json:"value,omitempty"`
	Posted string `json:"posted,omitempty"`
}
