/*
 * OpenBankProject-Bank-Branch
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AddressJsonV300 struct {
	City string `json:"city,omitempty"`
	Line2 string `json:"line_2,omitempty"`
	State string `json:"state,omitempty"`
	Postcode string `json:"postcode,omitempty"`
	County string `json:"county,omitempty"`
	CountryCode string `json:"country_code,omitempty"`
	Line3 string `json:"line_3,omitempty"`
	Line1 string `json:"line_1,omitempty"`
}
