/*
 * OpenBankProject-API-Metric
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ConnectorMetricJson struct {
	ConnectorName string `json:"connector_name,omitempty"`
	Duration int32 `json:"duration,omitempty"`
	FunctionName string `json:"function_name,omitempty"`
	CorrelationId string `json:"correlation_id,omitempty"`
	Date string `json:"date,omitempty"`
}
