/*
 * OpenBankProject-Bank
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BankJson struct {
	Website string `json:"website,omitempty"`
	FullName string `json:"full_name,omitempty"`
	Logo string `json:"logo,omitempty"`
	Id string `json:"id,omitempty"`
	ShortName string `json:"short_name,omitempty"`
	BankRoutingJsonV121 *interface{} `json:"BankRoutingJsonV121,omitempty"`
	BankRouting * `json:"bank_routing,omitempty"`
}
