/*
 * OpenBankProject-Bank-Branch
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BranchJsonV300 struct {
	Name string `json:"name,omitempty"`
	PhoneNumber string `json:"phone_number,omitempty"`
	LocationJsonV140 *interface{} `json:"LocationJsonV140,omitempty"`
	Location * `json:"location,omitempty"`
	BranchType string `json:"branch_type,omitempty"`
	BranchRoutingJsonV141 *interface{} `json:"BranchRoutingJsonV141,omitempty"`
	BranchRouting * `json:"branch_routing,omitempty"`
	DriveUp * `json:"drive_up,omitempty"`
	MoreInfo string `json:"more_info,omitempty"`
	BankId string `json:"bank_id,omitempty"`
	Id string `json:"id,omitempty"`
	MetaJsonV140 *interface{} `json:"MetaJsonV140,omitempty"`
	Meta * `json:"meta,omitempty"`
	Lobby * `json:"lobby,omitempty"`
	AccessibleFeatures string `json:"accessibleFeatures,omitempty"`
	Address * `json:"address,omitempty"`
	IsAccessible string `json:"is_accessible,omitempty"`
}
