/*
 * OpenBankProject-Card
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PostPhysicalCardJson struct {
	Allows *Array `json:"allows,omitempty"`
	ExpiresDate string `json:"expires_date,omitempty"`
	Networks *Array `json:"networks,omitempty"`
	IssueNumber string `json:"issue_number,omitempty"`
	ReplacementJSON *interface{} `json:"ReplacementJSON,omitempty"`
	Replacement * `json:"replacement,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	Collected string `json:"collected,omitempty"`
	Technology string `json:"technology,omitempty"`
	AccountId string `json:"account_id,omitempty"`
	PinReset *Array `json:"pin_reset,omitempty"`
	SerialNumber string `json:"serial_number,omitempty"`
	ValidFromDate string `json:"valid_from_date,omitempty"`
	BankCardNumber string `json:"bank_card_number,omitempty"`
	NameOnCard string `json:"name_on_card,omitempty"`
	Posted string `json:"posted,omitempty"`
}
