/*
 * OpenBankProject-User
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MeetingKeysJson struct {
	CustomerToken string `json:"customer_token,omitempty"`
	StaffToken string `json:"staff_token,omitempty"`
	SessionId string `json:"session_id,omitempty"`
}
