/*
 * OpenBankProject-Bank
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BankJsonv220 struct {
	NationalIdentifier string `json:"national_identifier,omitempty"`
	FullName string `json:"full_name,omitempty"`
	SwiftBic string `json:"swift_bic,omitempty"`
	LogoUrl string `json:"logo_url,omitempty"`
	Id string `json:"id,omitempty"`
	ShortName string `json:"short_name,omitempty"`
	BankRouting * `json:"bank_routing,omitempty"`
	WebsiteUrl string `json:"website_url,omitempty"`
}
