/*
 * OpenBankProject-User
 *
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2018. Licensed under the AGPL and commercial licences.
 *
 * API version: v3_1_0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EntitlementRequestJson struct {
	EntitlementRequestId string `json:"entitlement_request_id,omitempty"`
	RoleName string `json:"role_name,omitempty"`
	BankId string `json:"bank_id,omitempty"`
	UserJsonV200 *interface{} `json:"UserJsonV200,omitempty"`
	User * `json:"user,omitempty"`
	Created string `json:"created,omitempty"`
}
